AWSTemplateFormatVersion: 2010-09-09
Description: Fargate CI/CD sample VPC component.

Parameters: 

  Stage: 
    Type: String
    Default: dev
    Description: Deploy stage.

  AppName: 
    Type: String
    Default: cicd-s
    Description: Application name.

Resources:

  #############################################
  # VPC
  #############################################

  Vpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.123.2.0/23
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-vpc

  #############################################
  # Subnet
  #############################################

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: 10.123.3.0/25
      MapPublicIpOnLaunch: true
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-public-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.123.3.128/25
      MapPublicIpOnLaunch: true
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-public-2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: 10.123.2.0/25
      MapPublicIpOnLaunch: false
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-private-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.123.2.128/25
      MapPublicIpOnLaunch: false
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-private-2

  #############################################
  # Route Table
  #############################################

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-public-rt

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-private-rt-1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-private-rt-2

  #############################################
  # Internet Gateway
  #############################################

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${Stage}-igw

  #############################################
  # Association
  #############################################

  InternetGatewayAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref Vpc

  PublicRouteTableAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicRouteTableAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PrivateRouteTableAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1

  PrivateRouteTableAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnet2

  #############################################
  # Route
  #############################################

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # EIPが足りないのでコメントアウト

  # PrivateRoute1:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref PrivateRouteTable1
  #     DestinationCidrBlock: 0.0.0.0/0
  #     NatGatewayId: !Ref NATGateway1
  
  # PrivateRoute2:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref PrivateRouteTable2
  #     DestinationCidrBlock: 0.0.0.0/0
  #     NatGatewayId: !Ref NATGateway2

  #############################################
  # NAT
  #############################################

  # EIPが足りないのでコメントアウト

  # NATGatewayEIP1:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc

  # NATGatewayEIP2:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc

  # NATGateway1:
  #   Type: AWS::EC2::NatGateway
  #   Properties: 
  #     AllocationId: !GetAtt NATGatewayEIP1.AllocationId 
  #     SubnetId: !Ref PublicSubnet1

  # NATGateway2:
  #   Type: AWS::EC2::NatGateway
  #   Properties: 
  #     AllocationId: !GetAtt NATGatewayEIP2.AllocationId 
  #     SubnetId: !Ref PublicSubnet2

  #############################################
  # VPC Endpoint
  #############################################

  VpcS3EndPoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      VpcId: !Ref Vpc
      RouteTableIds:
        - !Ref PrivateRouteTable1
        - !Ref PrivateRouteTable2
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway

  VpcEcrDkrEndPoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      VpcId: !Ref Vpc
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      VpcEndpointType: Interface

Outputs:

  VPC:
    Description: VPC
    Value: !Ref Vpc
    Export:
      Name: !Sub ${AppName}-${Stage}-vpc

  PublicSubnet1:
    Description: Public Subnet 1
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${AppName}-${Stage}-public-1

  PublicSubnet2:
    Description: Public Subnet 2
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${AppName}-${Stage}-public-2

  PrivateSubnet1:
    Description: Private Subnet 1
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${AppName}-${Stage}-privagte-1

  PrivateSubnet2:
    Description: Private Subnet 2
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${AppName}-${Stage}-private-2

  VPCCider:
    Description: VPCCider
    Value: !GetAtt Vpc.CidrBlock
    Export:
      Name: !Sub ${AppName}-${Stage}-vpc-cider
